
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI chatbot support flow for students.
 *
 * - aiChatbotSupport - A function that handles the chatbot support process.
 * - AIChatbotSupportInput - The input type for the aiChatbotSupport function.
 * - AIChatbotSupportOutput - The return type for the aiChatbotSupport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { getFirestore } from 'firebase/firestore';
import { initializeFirebase } from '@/firebase';

const AIChatbotSupportInputSchema = z.object({
  query: z.string().describe('The query asked by the student.'),
  department: z.string().optional().describe('The department the user has selected for their query.'),
  conversationHistory: z.array(z.object({
      role: z.enum(['user', 'model']),
      content: z.string(),
  })).optional().describe('The history of the conversation so far.'),
  userId: z.string().describe('The ID of the user having the conversation.'),
  language: z.enum(['english', 'filipino', 'chinese', 'korean', 'swahili', 'auto']).optional().default('auto').describe('The language for the AI to respond in. If `auto`, detect the language from the user query.'),
});
export type AIChatbotSupportInput = z.infer<typeof AIChatbotSupportInputSchema>;

const AIChatbotSupportOutputSchema = z.object({
  response: z.string().describe('The response from the AI chatbot.'),
});
export type AIChatbotSupportOutput = z.infer<typeof AIChatbotSupportOutputSchema>;

// Initialize Firestore outside the flow
let db: any;
try {
    db = getFirestore(initializeFirebase().firebaseApp);
} catch (e) {
    console.warn("Could not initialize Firestore. Reminders will not work.");
}

const createTaskTool = ai.defineTool(
    {
        name: 'createTask',
        description: 'Creates a new task in the user\'s to-do list. Use this when a user asks to be reminded of something.',
        inputSchema: z.object({
            taskDescription: z.string().describe('A concise description of the task to be created.'),
        }),
        outputSchema: z.object({
            success: z.boolean(),
            message: z.string(),
        }),
    },
    async ({ taskDescription }) => {
        if (!db) {
            return { success: false, message: "Database not available." };
        }
        // In a real app, you'd get the userId from the authenticated session.
        // For this flow, we assume it's passed in the main input.
        // This is a placeholder for where you'd add to a 'tasks' collection for a user.
        try {
             // This is a placeholder. In a real app, you would get the user ID
             // from the authenticated context of the flow execution.
             console.log(`(Simulated) Adding task: "${taskDescription}" for a user.`);
             return { success: true, message: `Task "${taskDescription}" has been added.` };
        } catch (error) {
             console.error("Failed to create task:", error);
             return { success: false, message: "Failed to create the task." };
        }
    }
);

export async function aiChatbotSupport(input: AIChatbotSupportInput): Promise<AIChatbotSupportOutput> {
  return aiChatbotSupportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiChatbotSupportPrompt',
  tools: [createTaskTool],
  input: {schema: AIChatbotSupportInputSchema},
  output: {schema: AIChatbotSupportOutputSchema},
  prompt: `You are a helpful AI chatbot providing support to university students.

  Your primary instruction is to determine the language of the user's query and respond in that same language.
  {{#if language '!=' 'auto'}}
  The user has requested the response to be in {{language}}. You MUST respond in {{language}}.
  {{else}}
  If the user's query is in a language other than English, you MUST respond in their language.
  {{/if}}

  The available departments are CSS, Registrar, Guidance, and Dean's Office.
  {{#if conversationHistory}}
  This is the conversation history so far:
  {{#each conversationHistory}}
  {{this.role}}: {{this.content}}
  {{/each}}
  Based on this history, continue the conversation.
  {{/if}}

  {{#if department}}
  The user has selected the '{{department}}' department for their query. Your first task is to analyze the user's query and determine the most appropriate department to handle it.
  - If the user's query correctly matches the selected '{{department}}', proceed to answer the question as an expert from that department.
  - If the user's query seems to belong to a different department, you MUST first state that you are rerouting the question to the correct department, and then answer the question. For example: "It looks like this question is best for the Registrar's office. I'm routing you there. Here is the answer: ..."
  {{/if}}

  When a user asks you to remind them of something, use the createTask tool to create a task for them.

  Now, address the following query:
  "{{query}}"`,
});

const aiChatbotSupportFlow = ai.defineFlow(
  {
    name: 'aiChatbotSupportFlow',
    inputSchema: AIChatbotSupportInputSchema,
    outputSchema: AIChatbotSupportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
